### ISSUE TITLE
Create new tag 0.3.2

### ISSUE THREAD

**Issue by alecsammon** [giantjs/giant-transport#1]
Hi,

Tag 0.3.1 in this repo collides with 0.3.1 in giant-utils as they both provide toThrottler. I see that you have fixed this in the latest commit to this repo.

Is it possible to update the tag this repo also?

Is there a better way of me using the giant libraries to prevent these incompatibilities? Should I be referencing master, or commits in package.json instead?

**Comment by danstocker** [comment]
What should have happened is to raise minor version on all modules and document breaking changes.
Coming up.

**Comment by alecsammon** [comment]
Hmm - sorry - creating complication for you.

No rush - thank you.

**Comment by danstocker** [comment]
Version v0.4.0 released. http://www.giantjs.org/change-log.html#v0-4-0
